# Generated by Django 5.2.5 on 2025-08-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_course_alter_student_age_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
